modLoader = "javafml"
loaderVersion = "[${forge_version},)"
issueTrackerURL = "https://github.com/NotSoEpic/deepdrilling"
license = "MIT"

[[mods]]
modId = "deepdrilling"
version = "${version}"
displayName = "Deep Drilling"
authors = "beeisyou"
description = '''
An addon for Create, adding powerful drills that extract ores from deep within the earth
'''
logoFile = "icon.png"

[[dependencies.deepdrilling]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.deepdrilling]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.deepdrilling]]
modId="create"
mandatory=true
versionRange="${create_version}"
ordering="NONE"
side="BOTH"